// [
//   {
//     camis: "50015564",
//     dba: "ST GEORGE TAVERN RESTAURANT & BAR",
//     boro: "Manhattan",
//     building: "103",
//     street: "WASHINGTON STREET",
//     zipcode: "10006",
//     phone: "2122409868",
//     cuisine_description: "Asian/Asian Fusion",
//     inspection_date: "2022-04-19T00:00:00.000",
//     action: "Violations were cited in the following area(s).",
//     violation_code: "02A",
//     violation_description: "Food not cooked to required minimum temperature.",
//     critical_flag: "Critical",
//     score: "12",
//     grade: "A",
//     grade_date: "2022-04-19T00:00:00.000",
//     record_date: "2025-02-20T06:00:13.000",
//     inspection_type: "Cycle Inspection / Initial Inspection",
//     latitude: "40.708450716651",
//     longitude: "-74.014279788237",
//     community_board: "101",
//     council_district: "01",
//     census_tract: "001300",
//     bin: "1001045",
//     bbl: "1000530003",
//     nta: "MN25",
//   },
//   {
//     camis: "40538061",
//     dba: "COSMOS RESTAURANT",
//     boro: "Bronx",
//     building: "726",
//     street: "EAST TREMONT AVENUE",
//     zipcode: "10457",
//     phone: "7182991925",
//     cuisine_description: "American",
//     inspection_date: "2025-01-10T00:00:00.000",
//     action: "Violations were cited in the following area(s).",
//     violation_code: "02A",
//     violation_description:
//       "Time/Temperature Control for Safety (TCS) food not cooked to required minimum internal temperature.   • Poultry, poultry parts, ground and comminuted poultry, all stuffing containing poultry, meats, fish or ratites to or above 165 °F for 15 seconds with no interruption of the cooking process   • Ground meat, and food containing ground and comminuted meat, to or above 158 °F for 15 seconds with no interruption of the cooking process, except per individual customer request  • Pork, any food containing pork to or above 150 °F for 15 seconds  • Mechanically tenderized or injected meats to or above 155 °F.  • Whole meat roasts and beef steak to or above required temperature and time except per individual customer request  • Raw animal foods cooked in microwave to or above165 °F, covered, rotated or stirred   • All other foods to or above 140 °F for 15 seconds; shell eggs to or above 145 °F for 15 seconds except per individual customer request.",
//     critical_flag: "Critical",
//     score: "12",
//     grade: "A",
//     grade_date: "2025-01-10T00:00:00.000",
//     record_date: "2025-02-20T06:00:13.000",
//     inspection_type: "Cycle Inspection / Initial Inspection",
//     latitude: "40.844989166896",
//     longitude: "-73.890304453456",
//     community_board: "206",
//     council_district: "15",
//     census_tract: "036901",
//     bin: "2009978",
//     bbl: "2029500061",
//     nta: "BX17",
//   },
//   {
//     camis: "40384458",
//     dba: "DREAM PIZZA",
//     boro: "Queens",
//     building: "3767",
//     street: "JUNCTION BOULEVARD",
//     zipcode: "11368",
//     phone: "7189431599",
//     cuisine_description: "Pizza",
//     inspection_date: "2023-11-27T00:00:00.000",
//     action: "Violations were cited in the following area(s).",
//     violation_code: "02A",
//     violation_description:
//       "Time/Temperature Control for Safety (TCS) food not cooked to required minimum internal temperature.   • Poultry, poultry parts, ground and comminuted poultry, all stuffing containing poultry, meats, fish or ratites to or above 165 °F for 15 seconds with no interruption of the cooking process   • Ground meat, and food containing ground and comminuted meat, to or above 158 °F for 15 seconds with no interruption of the cooking process, except per individual customer request  • Pork, any food containing pork to or above 150 °F for 15 seconds  • Mechanically tenderized or injected meats to or above 155 °F.  • Whole meat roasts and beef steak to or above required temperature and time except per individual customer request  • Raw animal foods cooked in microwave to or above165 °F, covered, rotated or stirred   • All other foods to or above 140 °F for 15 seconds; shell eggs to or above 145 °F for 15 seconds except per individual customer request.",
//     critical_flag: "Critical",
//     score: "22",
//     record_date: "2025-02-20T06:00:13.000",
//     inspection_type: "Cycle Inspection / Initial Inspection",
//     latitude: "40.750340064517",
//     longitude: "-73.870112251068",
//     community_board: "403",
//     council_district: "21",
//     census_tract: "037500",
//     bin: "4043853",
//     bbl: "4017590035",
//     nta: "QN26",
//   },
// ];
